language: node_js
node_js:
  - lts/*

install:
  - npm i lerna 
  - npm run bs 
  - npm run build:1
script:
  - npm run build:2

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master
  target_branch: travis
  local_dir: packages/chat/dist
