language: node_js
node_js:
  - lts/*

install:
  - npm i lerna 
  - npm run bs 
  - npm run build:0:ui
  - npm run build:1:music-player
  - npm run build:2:wiichat
script:
  - npm run deploy:copy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master
  target_branch: travis
  local_dir: packages/wiichat/dist
